import { AsyncLocalStorage } from 'async_hooks';

interface RequestContext {
  correlationId: string;
  /** Transaction ID — generated by the frontend and threaded through all calls. */
  transactionId?: string;
}

export const asyncContext = new AsyncLocalStorage<RequestContext>();

export function getCorrelationId(): string | undefined {
  return asyncContext.getStore()?.correlationId;
}

export function getTransactionId(): string | undefined {
  return asyncContext.getStore()?.transactionId;
}

export function runWithContext<T>(
  correlationId: string,
  fn: () => T,
  transactionId?: string
): T {
  return asyncContext.run({ correlationId, transactionId }, fn);
}
