import { Request, Response, NextFunction } from 'express';
import { runWithContext } from '../lib/async-context';

/**
 * Header names — canonical (lowercase for Node.js header map).
 * These are the authoritative names for this project.
 *
 * Header reference (issue #1154):
 *
 * | Header              | Direction        | Description                                            |
 * |---------------------|------------------|--------------------------------------------------------|
 * | X-Correlation-Id    | bi-directional   | Per-request trace ID (generated by backend if absent)  |
 * | X-Transaction-Id    | frontend → backend → outbound | Logical tx ID set by the frontend page load, propagated through every service call |
 * | X-Request-Id        | backend → client | Unique ID for the individual HTTP request              |
 */
export const HEADER_CORRELATION_ID = 'x-correlation-id' as const;
export const HEADER_TRANSACTION_ID = 'x-transaction-id' as const;
export const HEADER_REQUEST_ID    = 'x-request-id' as const;

interface LogEntry {
  timestamp: string;
  method: string;
  path: string;
  statusCode: number;
  responseTime: number;
  userAgent?: string;
  ip?: string;
  requestId?: string;
  correlationId?: string;
  transactionId?: string;
  txHash?: string;
}

export const requestLoggingMiddleware = (
  req: Request,
  res: Response,
  next: NextFunction
): void => {
  const startTime = Date.now();
  const requestId =
    (req.headers[HEADER_REQUEST_ID] as string) ||
    `req_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;

  // Propagate or generate correlation ID (frontend passes x-correlation-id)
  const correlationId =
    (req.headers[HEADER_CORRELATION_ID] as string) || requestId;

  // Transaction ID — generated once per logical frontend flow and forwarded
  // through every backend/outbound call unchanged.
  const transactionId =
    (req.headers[HEADER_TRANSACTION_ID] as string) || undefined;

  // Attach IDs to request object and response headers
  req.headers[HEADER_REQUEST_ID]    = requestId;
  req.headers[HEADER_CORRELATION_ID] = correlationId;
  (req as any).correlationId  = correlationId;
  (req as any).transactionId  = transactionId;

  res.setHeader('X-Request-Id',    requestId);
  res.setHeader('X-Correlation-Id', correlationId);
  // Echo the transaction ID back only if the client sent one
  if (transactionId) {
    res.setHeader('X-Transaction-Id', transactionId);
  }

  // Run the remainder of the request pipeline inside the async context so that
  // every downstream log call can retrieve both IDs without threading them
  // through function arguments.
  runWithContext(correlationId, () => {
    // Capture response
    res.on('finish', () => {
      const responseTime = Date.now() - startTime;
      // tx hash may be present in body or query (read-only, never log signed XDR)
      const txHash =
        (req.body?.txHash as string | undefined) ||
        (req.query?.txHash as string | undefined);

      const logEntry: LogEntry = {
        timestamp: new Date().toISOString(),
        method: req.method,
        path: req.originalUrl || req.url,
        statusCode: res.statusCode,
        responseTime,
        userAgent: req.headers['user-agent'],
        ip: req.ip || req.socket.remoteAddress,
        requestId,
        correlationId,
        ...(transactionId && { transactionId }),
        ...(txHash && { txHash }),
      };

      const logMessage = JSON.stringify(logEntry);

      if (res.statusCode >= 500) {
        console.error(logMessage);
      } else if (res.statusCode >= 400) {
        console.warn(logMessage);
      } else {
        console.log(logMessage);
      }
    });

    next();
  }, transactionId);
};
